# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About the Program
    url: /#program
    weight: 20
  - name: Testimonials
    url: /#tetsimonials
    weight: 30
  - name: Meet the Founder
    url: /#founder
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50

